bible/urls.py
from django.urls import path
from . import views

app_name = "bible"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('feed', views.FeedView.as_view(), name='feed'),
    path('login', views.LogInView.as_view(), name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('logout', views.LogOutView.as_view(), name='logout'),
    path('kick/<int:receiver_id>', views.kick, name='kick'),
    path('send/<int:receiver_id>', views.send, name='send'),
]

hackathon/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bible/', include('bible.urls')),
]

bible/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    coins = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

class Verse(models.Model):
    content = models.CharField(max_length=2000)
    source = models.CharField(max_length=50)

    def __str__(self):
        return self.source

class Kick(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    verse = models.ForeignKey(Verse, on_delete=models.CASCADE)

bible/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .models import UserProfile, Verse, Kick
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class IndexView(generic.View):
    template_name = 'bible/index.html'

    def get(self, request, *args, **kwargs):
        userCreationForm = UserCreationForm()
        return render(request, self.template_name, {"form": UserCreationForm})


class FeedView(LoginRequiredMixin, generic.View):
    template_name = 'bible/feed.html'

    def get(self, request, *args, **kwargs):
        feed = Kick.objects.filter(receiver=request.user)
        user = User.objects.all().exclude(username=request.user.username)
        context = {
            'feeds': feed,
            'users': user,
        }
        return render(request, self.template_name, context)


class LogInView(generic.View):

    def post(self, request, *args, **kwargs):
        print('SIGNING IN')
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('bible:feed')
        else:
            # Return an 'invalid login' error message
            f = UserCreationForm()
            context = {
                'error_message': "Incorrect username or password.",
                'form': f,
            }
            return render(request, 'bible/index.html', context)


class SignUpView(generic.View):
    def post(self, request, *args, **kwargs):
        print('Signing up')
        username = request.POST['username']
        password = request.POST['password1']
        f = UserCreationForm(request.POST)
        if f.is_valid():
            user = User.objects.create_user(
                username=username, password=password)
            user = authenticate(request, username=username, password=password)
            userProfile = UserProfile(user=user)
            if user is not None:
                userProfile.save()
                user.save()
                login(request, user)
            return redirect('bible:feed')

        else:
            f = UserCreationForm()
            return render(request, 'bible/index.html', {"form": f})


class LogOutView(generic.View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('bible:index')


# class KickView(LoginRequiredMixin, generic.View):
#     template_name = 'bible/kick.html'

#     def post(self, request, *args, **kwargs):
#         receiver_pk = request.POST['pk']
#         verse_id = request.POST['verse_id']
#         verse = Verse.objects.get(pk=verse_id)
#         receiver = User.objects.get(pk=pk)
#         kick = Kick(sender=request.user, receiver=receiver, verse=verse)
#         kick.save()
#         return redirect('bible:feed')

def kick(request, receiver_id):
    verse = Verse.objects.all()
    receiver = User.objects.get(pk=receiver_id)
    context = {
        'verses': verse,
        'receiver': receiver,
    }
    return render(request, 'bible/kick.html', context)

def send(request, receiver_id):
    if(request.user.userprofile.coins < 1):
        feed = Kick.objects.filter(receiver=request.user)
        user = User.objects.all().exclude(username=request.user.username)
        context = {
            'feeds': feed,
            'users': user,
            'low_coins' :"Sorry, you have insufficient coins.",
        }
        return render(request,'bible/feed.html',context)
    else:
        request.user.userprofile.coins -= 1
        request.user.userprofile.save()
        receiver = User.objects.get(pk=receiver_id)
        receiver.userprofile.coins +=  5
        receiver.userprofile.save()
        verse = Verse.objects.get(pk=request.POST['verse'])
        kick = Kick(sender=request.user, receiver=receiver, verse=verse)
        kick.save()
        return redirect('bible:feed')

bible/templates/bible/feed.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>FEED</title>
  	<link href="{% static 'bible/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
	{% if low_coins %}
		<script> alert("Sorry you have insufficient coins.")</script>
	{% endif %}
	<div id="content-container">
		<div id="left-panel">
		 <div id="personal-details-container">
		   <div class="header-text">
		    BIBLE
		   </div>
		   <div class="subheader-text">
		     {{ request.user.username }}
		     Coins : {{request.user.userprofile.coins}}
		   </div>
		   <a href="{% url 'bible:logout' %}"><small>Sign Out</small></a>
		 </div>
		 <div class="friends-label-text"><h1 class="large padding20">Your friends</h1></div>
		 <div id="friend-list-panel-container">
		   <div class="friend-list-container">
		   		{% for user in users %}
					<div class="friend-name-container">
						<div class="friend-name truncate"> {{ user.username }}</div> 
						<a class="click-button" href="/bible/kick/{{user.id}}"> KICK </a></div>
				{% endfor %}
		  	</div>
		  </div>
		</div>
		<div id="right-panel">
		 <div id="feed-container">
		   <h1>Your daily verses from your Acquaintances!</h1>
		   <div id="verses-list">
				{% for feed in feeds %}
				<div class="verse-post">
		           <div class="verse-sharer"> {{ feed.sender.username }}</div>
		           <div class="verse-text"> {{ feed.verse.content }}</div>
		           <div class="verse-source"> {{ feed.verse.source }}</div>
		     	</div>
				{% endfor %}
		   </div>
		 </div>
		</div>
		</div>
	 </div>
	}
</body>
 </html>

bible/templates/bible/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>INDEX</title>

  	<link href="{% static 'bible/css/styles.css' %}" rel="stylesheet"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
	<div id="content-container">
		<div id="left-panel-2">
			<h1> Sign Up </h1>

			<form action="{% url 'bible:signup' %}" method="POST">
				{% csrf_token %}
				<form action="/bible/signup" method="POST">
				<p class='loginformfield'>
					<label for="id_username">Username:</label> 
					<input class='field' type="text" name="username" autofocus required maxlength="150" id="id_username" /> 
					<span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
				</p>
				<p  class='loginformfield'>
					<label for="id_password1">Password:</label> 
					<input class='field' type="password" name="password1" required id="id_password1" />
					 <div class="helptext">
					 	<ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul>
					 </div>
				</p>
				<p  class='loginformfield'>
					<label for="id_password2">Password confirmation:</label>
					 <input class='field' type="password" name="password2" required id="id_password2" /> 
					 <div class="helptext">Enter the same password as before, for verification.
					 </div>
				</p  class='loginformfield'>
				<input type='hidden' name='csrfmiddlewaretoken' value='SoaGtBdvVLXXGjZMSiVgGNquyPJoT33f762XmKt8qQkjmkuIF4eisfSjmxxtbRTv' />
				<div class="form-group">
			      <button class="click-button alignselfcenter margintop30" type="submit" >Sign Up</button>
			    </div>
			</form>
		</div>
		<div id="right-panel-2">

			<h1> Log In </h1>
			<div class="error_message">
				{% if error_message %}
					{{error_message}}
				{% endif%}
			</div>
			<form action="{% url 'bible:login' %}" method="POST">
			    {% csrf_token %}
			    <div class="form-group loginformfield">
			      <label for="username">Username</label>
			      <input class='field' type="text" id="username" name="username" required="required"/>
			    </div>
			    <div class="form-group loginformfield">
			      <label for="password">Password</label>
			      <input class='field' type="password" id="password1" name="password1" required="required"/>
			    </div>
				<div class="form-group loginformfield">
				  <button class="click-button alignselfcenter margintop30" type="submit"" >Log In</button>
				</div>
			</form>
		</div>
	</div>

	{% if error_message %}
		{{error_message}}
	{% endif%}
	
</body>
</html>

bible/templates/bible/kick.html
{% load static %}

<html>
<head><link href="{% static 'bible/css/styles.css' %}" rel="stylesheet"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
</head>
<body>
	<div class='center-panel max-width-800'>
		<form action="/bible/send/{{receiver.id}}" method = "POST">
			{% csrf_token %}
			<h1> This verse is for {{ receiver.username}}</h1>
			<!-- I know inline styles are not advisable i'm sorry huhuhu -->
		<select class = "selectpicker" style="font-size: 1.2em; width: 70%" name="verse">
				{% for verse in verses %}
				<option style="font-size: 1.2em; width: inherit" value="{{verse.pk}}">{{verse.content}}</option>
				{% endfor %}
			</select>
			<div class="form-group">
		      <button class="click-button margintop30" type="submit"" >Kick</button>
		    </div>
		</form>
	</div>
</body>
</html>